services:
  db:
    image: postgres:12.18-bullseye
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: /run/secrets/db-password
    secrets:
      - db-password
    networks:
      - java-postgres
    expose:
      - 5432
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgresVolume:/var/lib/postgresql/data

  backend:
    build: crud-jdbc
    restart: on-failure
    ports:
      - 8080:8080
      - 8001:8001 # remote debugging
    networks:
      - java-postgres
    environment:
      POSTGRES_DB_USER: postgres
      DB_URL: jdbc:postgresql://db:5432/postgres
      POSTGRES_PASSWORD: /run/secrets/db-password
    secrets:
      - db-password
  jenkins:
    image: jenkins/jenkins:jdk17
    ports:
      - 8003:8080
      # - 5000:5000
    restart: on-failure
    volumes:
      - jenkinsVolume:/var/jenkins_home
secrets:
  db-password:
    file: db-password.txt
networks:
  java-postgres:
volumes:
  postgresVolume:
  jenkinsVolume: