services:
  sonar:
      image: sonarqube:lts-community
      ports:
        - 9000:9000
      restart: on-failure
      volumes:
        - sonarqube_data:/opt/sonarqube/data
        - sonarqube_logs:/opt/sonarqube/logs
        - sonarqube_extensions:/opt/sonarqube/extensions
volumes:
    sonarqube_data:
    sonarqube_logs:
    sonarqube_extensions: